"""
3D Depth-Map Image to DXF Converter
Interprets a grayscale image as a height/depth field and generates:
  - A 3D triangulated MESH entity (DXF R2000+)
  - Optional point cloud of sampled vertices
  - Optional contour lines at equidistant Z slices
"""

import io
import cv2
import numpy as np
import ezdxf
from ezdxf.render import MeshBuilder
from PIL import Image


def convert_3d(image_bytes: bytes, settings: dict) -> bytes:
    """
    Convert a depth-map image to a 3D DXF MESH.

    Args:
        image_bytes: Raw image file bytes
        settings: Dict with keys:
            - dxf_version (str): e.g. 'R2010', 'R2000'
            - scale_xy (float): XY spacing between grid points
            - scale_z (float): Maximum Z height
            - invert (bool): invert depth (dark = high vs bright = high)
            - resolution (int): downsample to this max dimension (32–512)
            - output_type (str): 'mesh', 'pointcloud', 'contours', 'all'
            - blur_radius (int): pre-smoothing blur radius
            - contour_levels (int): number of Z contour slices

    Returns:
        DXF file content as bytes
    """
    # --- Parse settings ---
    dxf_version    = settings.get("dxf_version", "R2010")
    scale_xy       = float(settings.get("scale_xy", 1.0))
    scale_z        = float(settings.get("scale_z", 50.0))
    invert         = bool(settings.get("invert", False))
    resolution     = int(settings.get("resolution", 128))
    output_type    = settings.get("output_type", "mesh")
    blur_radius    = int(settings.get("blur_radius", 3))
    contour_levels = int(settings.get("contour_levels", 10))

    # --- Load & preprocess ---
    pil_image = Image.open(io.BytesIO(image_bytes)).convert("L")

    # Resize to target resolution (keep aspect ratio)
    w, h = pil_image.size
    if max(w, h) > resolution:
        ratio = resolution / max(w, h)
        new_w = max(2, int(w * ratio))
        new_h = max(2, int(h * ratio))
        pil_image = pil_image.resize((new_w, new_h), Image.LANCZOS)

    depth = np.array(pil_image, dtype=np.float32)

    # Blur to smooth the depth field
    if blur_radius > 1:
        k = blur_radius if blur_radius % 2 == 1 else blur_radius + 1
        depth = cv2.GaussianBlur(depth, (k, k), 0)

    # Normalize to [0, 1]
    dmin, dmax = depth.min(), depth.max()
    if dmax - dmin < 1e-6:
        raise ValueError("Depth map has no variation — image appears flat or uniform.")
    depth = (depth - dmin) / (dmax - dmin)

    if invert:
        depth = 1.0 - depth

    rows, cols = depth.shape

    # --- Build DXF document ---
    doc = ezdxf.new(dxf_version)
    msp = doc.modelspace()

    doc.layers.add("MESH",   color=5)   # blue
    doc.layers.add("POINTS", color=3)   # green
    doc.layers.add("CONTOURS", color=1) # red

    if output_type in ("mesh", "all"):
        _add_mesh(msp, depth, rows, cols, scale_xy, scale_z)

    if output_type in ("pointcloud", "all"):
        _add_point_cloud(msp, depth, rows, cols, scale_xy, scale_z, doc)

    if output_type in ("contours", "all"):
        _add_contour_lines(msp, depth, rows, cols, scale_xy, scale_z, contour_levels)

    # Metadata text
    msp.add_text(
        "Generated by Image2DXF Converter — 3D Mode",
        dxfattribs={
            "layer": "MESH",
            "height": 3.0,
            "insert": (0, -15, 0),
        }
    )

    # --- Serialize ---
    buffer = io.StringIO()
    doc.write(buffer)
    return buffer.getvalue().encode("utf-8")


def _add_mesh(msp, depth: np.ndarray, rows: int, cols: int,
              scale_xy: float, scale_z: float):
    """Build a triangulated surface mesh from the depth grid."""
    builder = MeshBuilder()

    # Add all grid vertices
    vertices = []
    for r in range(rows):
        for c in range(cols):
            x = c * scale_xy
            y = (rows - 1 - r) * scale_xy   # flip Y
            z = float(depth[r, c]) * scale_z
            vertices.append((x, y, z))
    builder.vertices = vertices

    # Triangulate each grid cell → 2 triangles
    for r in range(rows - 1):
        for c in range(cols - 1):
            tl = r * cols + c
            tr = r * cols + (c + 1)
            bl = (r + 1) * cols + c
            br = (r + 1) * cols + (c + 1)
            builder.add_face([tl, tr, br])
            builder.add_face([tl, br, bl])

    builder.render_mesh(msp, dxfattribs={"layer": "MESH"})


def _add_point_cloud(msp, depth: np.ndarray, rows: int, cols: int,
                     scale_xy: float, scale_z: float, doc):
    """Add 3D POINT entities representing the depth field."""
    doc.header["$PDMODE"] = 3     # X cross style
    doc.header["$PDSIZE"] = scale_xy * 0.4

    for r in range(rows):
        for c in range(cols):
            x = c * scale_xy
            y = (rows - 1 - r) * scale_xy
            z = float(depth[r, c]) * scale_z
            msp.add_point((x, y, z), dxfattribs={"layer": "POINTS"})


def _add_contour_lines(msp, depth: np.ndarray, rows: int, cols: int,
                       scale_xy: float, scale_z: float, levels: int):
    """Add horizontal contour lines at equidistant Z levels using OpenCV."""
    for lvl in range(1, levels + 1):
        z_val = (lvl / levels) * scale_z
        # Find pixels at this depth level
        z_norm = lvl / levels
        lo = max(0.0, z_norm - 0.5 / levels)
        hi = min(1.0, z_norm + 0.5 / levels)

        mask = ((depth >= lo) & (depth <= hi)).astype(np.uint8) * 255
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

        for cnt in contours:
            if len(cnt) < 2:
                continue
            pts_3d = []
            for pt in cnt:
                c_px = int(pt[0][0])
                r_px = int(pt[0][1])
                x = c_px * scale_xy
                y = (rows - 1 - r_px) * scale_xy
                pts_3d.append((x, y, z_val))

            if len(pts_3d) >= 2:
                # Write as 3D polyline
                msp.add_polyline3d(pts_3d, dxfattribs={"layer": "CONTOURS"})
