"""
2D Image to DXF Converter
Converts raster images to vector DXF by extracting contours via OpenCV
and writing them as LWPOLYLINE / SPLINE entities using ezdxf.
"""

import io
import cv2
import numpy as np
import ezdxf
from ezdxf.enums import TextEntityAlignment
from PIL import Image


def convert_2d(image_bytes: bytes, settings: dict) -> bytes:
    """
    Convert a 2D image to DXF format.

    Args:
        image_bytes: Raw image file bytes
        settings: Dict with keys:
            - threshold (int 0-255): binarization threshold
            - epsilon_factor (float): contour simplification factor (0.0001 – 0.01)
            - blur_radius (int): Gaussian blur radius (odd number)
            - dxf_version (str): e.g. 'R2010', 'R2000', 'R12'
            - invert (bool): invert image before processing
            - scale (float): scale factor for coordinates
            - use_canny (bool): use Canny edge detection vs threshold
            - layer_mode (str): 'single' or 'hierarchy' (multi-layer by contour depth)

    Returns:
        DXF file content as bytes
    """
    # --- Parse settings ---
    threshold    = int(settings.get("threshold", 128))
    eps_factor   = float(settings.get("epsilon_factor", 0.002))
    blur_radius  = int(settings.get("blur_radius", 3))
    dxf_version  = settings.get("dxf_version", "R2010")
    invert       = bool(settings.get("invert", False))
    scale        = float(settings.get("scale", 1.0))
    use_canny    = bool(settings.get("use_canny", False))
    layer_mode   = settings.get("layer_mode", "hierarchy")

    # --- Load image ---
    pil_image = Image.open(io.BytesIO(image_bytes)).convert("RGBA")
    # Flatten alpha onto white background
    background = Image.new("RGB", pil_image.size, (255, 255, 255))
    background.paste(pil_image, mask=pil_image.split()[3])
    gray = np.array(background.convert("L"))

    # --- Blur ---
    if blur_radius > 1:
        k = blur_radius if blur_radius % 2 == 1 else blur_radius + 1
        gray = cv2.GaussianBlur(gray, (k, k), 0)

    # --- Invert ---
    if invert:
        gray = cv2.bitwise_not(gray)

    # --- Edge / threshold ---
    if use_canny:
        lo = max(0, threshold - 30)
        hi = min(255, threshold + 30)
        binary = cv2.Canny(gray, lo, hi)
    else:
        _, binary = cv2.threshold(gray, threshold, 255, cv2.THRESH_BINARY_INV)

    # --- Morphological cleanup ---
    kernel = np.ones((2, 2), np.uint8)
    binary = cv2.morphologyEx(binary, cv2.MORPH_CLOSE, kernel)

    # --- Find contours ---
    retrieval_mode = cv2.RETR_TREE if layer_mode == "hierarchy" else cv2.RETR_EXTERNAL
    contours, hierarchy = cv2.findContours(binary, retrieval_mode, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        raise ValueError("No contours found in the image. Try adjusting the threshold.")

    # --- Build DXF ---
    doc = ezdxf.new(dxf_version)
    msp = doc.modelspace()

    # Define layers
    doc.layers.add("OUTLINE", color=7)      # white/black
    doc.layers.add("INNER",   color=4)      # cyan
    doc.layers.add("DETAIL",  color=3)      # green

    img_height = gray.shape[0]

    def assign_layer(depth: int) -> str:
        if depth == 0:
            return "OUTLINE"
        elif depth == 1:
            return "INNER"
        else:
            return "DETAIL"

    for idx, cnt in enumerate(contours):
        if len(cnt) < 2:
            continue

        # Simplify contour
        arc_len = cv2.arcLength(cnt, True)
        epsilon = eps_factor * arc_len
        approx = cv2.approxPolyDP(cnt, epsilon, True)

        if len(approx) < 2:
            continue

        # Scale and flip Y axis (DXF Y increases upward, image Y increases downward)
        points = []
        for pt in approx:
            x = float(pt[0][0]) * scale
            y = float(img_height - pt[0][1]) * scale   # flip Y
            points.append((x, y))

        # Determine layer
        layer = "OUTLINE"
        if layer_mode == "hierarchy" and hierarchy is not None:
            depth = _contour_depth(idx, hierarchy[0])
            layer = assign_layer(depth)

        # Write polyline
        if len(points) >= 2:
            msp.add_lwpolyline(points, close=True, dxfattribs={"layer": layer})

    # Add a metadata text comment
    msp.add_text(
        "Generated by Image2DXF Converter",
        dxfattribs={
            "layer": "OUTLINE",
            "height": 5 * scale,
            "insert": (0, -20 * scale),
        }
    )

    # --- Serialize to bytes ---
    buffer = io.StringIO()
    doc.write(buffer)
    return buffer.getvalue().encode("utf-8")


def _contour_depth(idx: int, hier: np.ndarray) -> int:
    """Compute nesting depth of contour at index idx."""
    depth = 0
    parent = hier[idx][3]
    while parent != -1 and depth < 10:
        depth += 1
        parent = hier[parent][3]
    return depth
